Fix "public" schema ownership
bitnami/bitnami-docker-postgresql pull request #290
Opened 2021-06-02 13:45 UTC by Sebor

**Description of the change**

Added additional command
```
```
to fix this [issue](<https://github.com/bitnami/bitnami-docker-postgresql/issues/289>)

**Benefits**

The "public" schema now has right owner

**Possible drawbacks**

-

**Applicable issues**

#289 

**Additional information**

2021-06-03 07:10 UTC, juan131 requested changes
Thanks so much for the contribution!! Could you please take a look to my comment and replicate the same changes in the branches `9.6`, `10`, `11`, and `12`?

2021-06-03 07:10 UTC, juan131 commented on 13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh
> +    info "Granting access to \"${POSTGRESQL_USERNAME}\" to the 'public' schema in database \"${POSTGRESQL_DATABASE}\""
The message is not quite accurate:
```suggestion
    info "Setting ownership for the 'public' schema database \"${POSTGRESQL_DATABASE}\" to \"${POSTGRESQL_USERNAME}\""
```

2021-06-03 08:49 UTC, Sebor commented
> Thanks so much for the contribution!! Could you please take a look to my comment and replicate the same changes in the branches `9.6`, `10`, `11`, and `12`?

Hi, @juan131!
Done

2021-06-04 05:55 UTC, juan131 approved these changes
Thanks!!! I'm sending your changes for internal review, I'll keep you updated about the progress

2021-06-07 09:28 UTC, merged

2021-06-07 09:28 UTC, juan131 commented
@Sebor the changes were accepted in the internal review, and new revisions of the PostgreSQL containers (on every branch) will be released within the next 24 hours including them.

Thanks again for this great contribution!